#!/bin/bash

set -eu
source hooks/lib.sh

log_success "Running cargo fmt hook"
if ! cargo fmt -- --check; then
    log_error 'There are some issues with your code, run `cargo fmt`'
    exit 1
fi

exit 0
